language: php

dist: trusty

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  sonarcloud:
    organization: uuf6429-github
    token: $SONAR_TOKEN
    branches:
      - master
      - Major-refactor

install:
  - composer remove "friendsofphp/php-cs-fixer" --dev --no-interaction
  - composer install --no-scripts --no-progress --no-interaction

script:
  - |
    ./vendor/bin/phpunit \
      --log-junit junit.xml \
      --coverage-clover clover.xml \
      --configuration phpunit.xml.dist
  - |
    [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ] \
    && sonar-scanner \
      "-Dsonar.projectVersion=$(git describe --tags)_PHP-$TRAVIS_PHP_VERSION" \
      "-Dsonar.projectKey=Force.com-Toolkit-for-PHP" \
      "-Dsonar.projectName=Force.com Toolkit for PHP" \
      "-Dsonar.projectKey=Force.com-Toolkit-for-PHP" \
      "-Dsonar.php.tests.reportPath=junit.xml" \
      "-Dsonar.php.coverage.reportPaths=clover.xml" \
      "-Dsonar.sources=./src" \
      "-Dsonar.tests=./test" \
    || true
