language: php

dist: trusty

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer remove "friendsofphp/php-cs-fixer" --no-interaction
  - composer install --no-scripts --no-progress --no-interaction

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
